### ISSUE TITLE
Typo in some case

### ISSUE THREAD

**Issue by khumam** [theanik/laravel-more-command#3]
I Love your project. But there are some misspelled. 

1. When I create view, the view created at `resource/` folder not `resources/`
2. When I create some module like service, there are misspelled on construct() declaration. And I checked the stub, then I think some stub also write constuct() than construct()

I hope you can fix the misspelled. 

Thank You

**Comment by theanik** [comment]
Hello Dear,
Thank you for creating the issue.
It has fixed.
Thank You

**Comment by khumam** [comment]
Thank you brother

**Comment by henriquecm** [comment]
When is this fix gonna be released?

**Comment by theanik** [comment]
> When is this fix gonna be released?
Hi, It's done.
https://github.com/theanik/laravel-more-command/releases/tag/v1.2.0
