### ISSUE TITLE
Typo namespace for Repository Interfaces

### ISSUE THREAD

**Issue by andreinocenti** [theanik/laravel-more-command#4]
When creating an repository with interface, eg: `php artisan make:repository UserRepository -i` 

The interface UserRepositoryInterface created comes with a typo in the namespace. 
It come as `namespace App\Repositorires\Interfaces` .
The "Repositorires" is wrong, with a R in the end

**Comment by theanik** [comment]
Thank you for creating the issue.
it's fixed, 
https://github.com/theanik/laravel-more-command/commit/aab76744edd18f3fdff240bf8bdd08daf9640985
